-- CreateEnum
CREATE TYPE "Status" AS ENUM ('NAO_PROCESSADO', 'PROCESSADO', 'EM_PROCESSAMENTO');

-- CreateTable
CREATE TABLE "fis_nota_fiscal_servico" (
    "id" SERIAL NOT NULL,
    "dt_created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dt_updated" TIMESTAMP(3) NOT NULL,
    "id_fis_empresas" TEXT NOT NULL,
    "ds_status" "Status",
    "ds_referencia" TEXT NOT NULL,
    "ds_munic_orgao" TEXT NOT NULL,
    "dt_competencia" TIMESTAMP(3) NOT NULL,
    "ds_nota_fiscal" INTEGER,
    "ds_serie_nota_fiscal" TEXT,
    "ds_tipo_nota_fiscal" TEXT,
    "dt_emissao" TIMESTAMP(3),
    "ds_optante_simples_nacional" TEXT,
    "ds_regime_especial_tributacao" TEXT,
    "ds_incentivo_fiscal" TEXT,
    "ds_iss_retido" TEXT,
    "ds_exigibilidade_iss" TEXT,
    "ds_item_lista_servico" TEXT,
    "ds_cnae" TEXT,
    "ds_tributacao_municipio" TEXT,
    "ds_discriminacao" TEXT,
    "ds_municipio" TEXT,
    "ds_pais" TEXT,
    "ds_identificacao_nao_exigibilidade" TEXT,
    "ds_municipio_incidencia" TEXT,
    "ds_processo" TEXT,
    "vl_servicos" DOUBLE PRECISION,
    "vl_deducoes" DOUBLE PRECISION,
    "vl_pis" DOUBLE PRECISION,
    "vl_cofins" DOUBLE PRECISION,
    "vl_inss" DOUBLE PRECISION,
    "vl_ir" DOUBLE PRECISION,
    "vl_csll" DOUBLE PRECISION,
    "vl_outras_retencoes" DOUBLE PRECISION,
    "vl_desconto_condicionado" DOUBLE PRECISION,
    "vl_desconto_incondicionado" DOUBLE PRECISION,
    "ds_nr_inscricao_municipal_prestador" TEXT,
    "ds_cnpj_prestador" TEXT,
    "ds_razao_social_prestador" TEXT,
    "ds_razao_social_tomador" TEXT,
    "ds_inscricao_municipal_tomador" TEXT,
    "ds_cpf_cnpj_tomador" TEXT,
    "ds_endereco_tomador" TEXT,
    "nr_endereco_tomador" TEXT,
    "ds_complemento_tomador" TEXT,
    "ds_bairro_tomador" TEXT,
    "ds_municipio_tomador" TEXT,
    "ds_uf_tomador" TEXT,
    "ds_cep_tomador" TEXT,
    "ds_telefone_tomador" TEXT,
    "ds_email_tomador" TEXT,
    "ds_obra_construcao_civil" TEXT,
    "ds_art_construcao_civil" TEXT,
    "ds_id_evento" TEXT,
    "ds_evento" TEXT,
    "ds_tipp_deducao" TEXT,
    "ds_deducao" TEXT,
    "dt_emissao_deducao" TIMESTAMP(3),
    "vl_dedutivel" DOUBLE PRECISION,
    "vl_utilizado_deducao" DOUBLE PRECISION,
    "ds_cd_municipio_gerador_nfse" TEXT,
    "ds_nr_nfse" TEXT,
    "ds_verificacao_nfse" TEXT,
    "ds_nr_nfe" TEXT,
    "ds_uf_nfe" TEXT,
    "ds_chave_acesso_nfe" TEXT,
    "ds_id_documento_outro" TEXT,
    "nr_cpf_cnpj_fornecedor" TEXT,
    "ds_nif_fornecedor_exterior" TEXT,
    "cd_pais_fornecedor_exterior" TEXT,

    CONSTRAINT "fis_nota_fiscal_servico_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "fis_nota_fiscal_servico" ADD CONSTRAINT "fis_nota_fiscal_servico_id_fis_empresas_fkey" FOREIGN KEY ("id_fis_empresas") REFERENCES "fis_empresas"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
